config/routes.rb
Rails.application.routes.draw do
  root 'calc#input'
  get 'calc/view'
  get 'calc/xml'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calc_controller.rb
# frozen_string_literal: true

# class for calculating input and writing it to database
class CalcController < ApplicationController
  def input; end

  def view
    @input = params[:less_than_number].to_i
    res = Result.find_by(input: @input)
    if res
      @result = ActiveSupport::JSON.decode(res.output)
    else
      @result = calculate(@input)
      add_to_db(@input, @result)
    end
  end

  def xml
    results = Result.all.map do |result|
      { input: result.input, output: result.output }
    end
    render xml: results
  end

  private

  def calculate(nmax)
    [*1..nmax].select { |num| (num**2).to_s.reverse == (num**2).to_s && num <= nmax }
              .map { |elem| [elem, elem**2] }
  end

  def add_to_db(input, result)
    local_res = Result.create input: input, output: ActiveSupport::JSON.encode(result)
    local_res.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calc_helper.rb
module CalcHelper
end

app/views/calc/input.html.erb
<h1>Страница ввода N</h1>
<%= form_tag("/calc/view.x", :method => "get") do %>
<%= label_tag("Введите число n:") %>
<%= number_field_tag(:less_than_number, nil, min: 1) %> <br/>
<%= submit_tag("Find palindroms") %>
<% end %>
<%= link_to "Show XML", calc_xml_path %>

app/views/calc/view.html.erb
<h1>Страница результата</h1>
<p>Изначальные данные:</p>
<p><%= @input %></p>
<p>Результат:</p>
<table>
  <tr>
    <th>Число</th>
    <th>Квадрат числа</th>
  </tr>
 <% @result.each do |number| %>
  <tr>
    <td><%= number[0] %></td>         
    <td><%= number[1] %></td>
  </tr>
  <% end %>
  <tr>
    <th>Количество чисел:</th>
    <th><%= @result.length %></th>
  </tr>
</table>
<p><%= @db %></p>
<br>
<%= link_to "Выбрать другое число", :root %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab11</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>